name: vault
version: master
version-script: git -C parts/vault/build describe --dirty | sed "s/v//g"
summary: Vault is a tool for securely accessing secrets.
description: |
  A modern system requires access to a multitude of secrets: database
  credentials, API keys for external services, credentials for service-oriented
  architecture communication, etc. Understanding who is accessing what secrets
  is already very difficult and platform-specific. Adding on key rolling,
  secure storage, and detailed audit logs is almost impossible without a custom
  solution. This is where Vault steps in.

grade: stable
confinement: strict

apps:
  vault:
    command: bin/vault
    plugs: [network, network-bind]

parts:
  vault:
    source: https://github.com/hashicorp/vault.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info vault | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git checkout "${last_committed_tag}"
        # XXX The snapcraft go plugin builds a link to the src dir, not to the
        # build dir. That might be a bug, but let's better checkout both to be
        # safe that we are not building the wrong thing. --elopio - 20171108
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      git apply $SNAPCRAFT_STAGE/etcd_export_tls_no_verify.patch
      snapcraftctl build
    plugin: go
    go-importpath: github.com/hashicorp/vault
    go-buildtags: [vault]
    build-packages: [git, g++, libsasl2-dev]
    after:
      - go
      - patches
  go:
    source-tag: go1.10.1
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*
